### ISSUE TITLE
Update containers in workflows to Fedora 39 and remove Fedora 37

### ISSUE THREAD

**Issue by kwk** [fedora-llvm-team/llvm-snapshots#214]
## TODOs

- [ ] [check-todays-snapshot.yml](https://github.com/kwk/llvm-daily-fedora-rpms/blob/850459981bcd1a587a17fa509efd0aba77f1a3c9/.github/workflows/check-todays-snapshot.yml#L37)
- [ ] [fedora-copr-build.yml](https://github.com/kwk/llvm-daily-fedora-rpms/blob/850459981bcd1a587a17fa509efd0aba77f1a3c9/.github/workflows/fedora-copr-build.yml#L39)
- [x] [tmt.yml](https://github.com/kwk/llvm-daily-fedora-rpms/blob/main/.github/workflows/tmt.yml#L12)
  * See #245
